name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install -r requirements.txt || { echo "Failed to install dependencies"; exit 1; }

    - name: List files for debugging
      run: |
        echo "Listing files"
        ls -R

    - name: Run the application
      run: |
        echo "Running the application"
        python app.py || { echo "Application run failed"; exit 1; }
