name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: List files for debugging
      run: |
        echo "Listing all files"
        ls -R
        echo "Current directory: $(pwd)"
        echo "Home directory: $HOME"

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        pip install Flask pandas joblib scikit-learn

    - name: Run the application
      run: |
        echo "Running the application"
        nohup python app.py &
        sleep 10
        curl http://127.0.0.1:5000
        pkill -f "python app.py"

